import type { Metadata } from 'next';
import {
	Geist,
	Geist_Mono,
	Moon_Dance,
	Red_Hat_Display,
} from 'next/font/google';
import './reset.css';
import './globals.scss';

// Context
import { ContextProvider } from './context/AppContext';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

const moondance = Moon_Dance({
	variable: '--font-moon-dance',
	weight: '400',
	subsets: ['latin'],
});

const redHatDisplay = Red_Hat_Display({
	variable: '--font-red-hat-display',
	weight: '400',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${moondance.variable} ${redHatDisplay.variable}`}
			>
				<ContextProvider>{children}</ContextProvider>
			</body>
		</html>
	);
}
